### ISSUE TITLE
Does it work with a Xcode 7 UI test target? 

### ISSUE THREAD

**Issue by ariok** [kylef/Mockingjay#26]
I'm trying to make Mockingjay working within a UI Test target but I cannot make it run properly. It seems that stubs are never used when the code runs from a UI Test target.

**Comment by sjmadsen** [comment]
UI testing runs apps in a different process than the tests, so you won't be able to stub out network calls.

**Comment by siemensikkema** [comment]
I'm using a workaround. In my UI test class:
```swift
override func setUp() {
	super.setUp()

	continueAfterFailure = false

	app = XCUIApplication()
	app.launchArguments = [LaunchArguments.StubNetworkResponses.rawValue,
		LaunchArguments.UseInMemoryDatabase.rawValue]
	app.launch()
}
```
With the following enum made available to both the UI test target and the main target:
```swift
internal enum LaunchArguments: String {
	case UseInMemoryDatabase
	case StubNetworkResponses
}
```
And in the main target:
```swift
internal func setUpNetworkStubbing(
	processInfoArguments: [String] = NSProcessInfo.processInfo().arguments) {
		guard processInfoArguments.contains(LaunchArguments.StubNetworkResponses.rawValue) else {
			return
		}
        // stub all you want here
}
```
which I call when my app finishes launching. (The default argument is for dependency injection while testing the stubbing function). Any JSON fixture files will need to be added to the main target instead of (or in addition to) the UI test target.
An additional benefit is that you can pass these arguments to the app while running using "Edit Scheme" to use your app with stubbed data.
As you can see, I use the same trick to force my app to use an in-memory database.

**Comment by mdio** [comment]
Are you using Mockingjay for the stubbing?
I can't seem to get it to work due to it's dependency on XCTest.

**Comment by siemensikkema** [comment]
@mdio Not anymore. I'm using OHHTTPStubs currently.

**Comment by kylef** [comment]
As I've mentioned in https://github.com/kylef/Mockingjay/issues/36#issuecomment-218245559, you can use Mockingjay without XCTest. Mockingjay doesn't strictly depend on XCTest.

You can depend on `Mockingjay/Core` via CocoaPods and then use the following API:

- `MockingjayProtocol.addStub(matcher, builder)`
- `MockingjayProtocol.removeStub(stub)`
- `MockingjayProtocol.removeAllStubs()`

Therefore you can use Mockingjay with UI test targets.

**Comment by borut-t** [comment]
How can i stub requests while using 3rd party http clients (e.g. Alamofire)?
Using the same code as for unit test doesn't work:
```Swift
let request = http(.post, uri: "path-to-request")
MockingjayProtocol.addStub(matcher: request, builder: json(["id": "1"]))
```
