### ISSUE TITLE
Xcode can't find stub or matcher now

### ISSUE THREAD

**Issue by istx25** [kylef/Mockingjay#28]
We have jsonData now but now Xcode is complaining that `stub` and `matcher` are unavailable. Not sure why.

```swift
import Foundation
import Mockingjay

class TestModel: NSObject {

    class func testRequest() {
        let path = NSBundle.mainBundle().pathForResource("Plaid", ofType: "json")
        let data = NSData(contentsOfFile: path!)!

        stub(matcher, builder: jsonData(data))
    }

}
```

Ideas?

<img width="296" alt="screen shot 2015-10-12 at 10 51 24 am" src="https://cloud.githubusercontent.com/assets/6799989/10434578/3c33a118-70cf-11e5-8d20-4cb9dd99d681.png">

**Comment by kylef** [comment]
@istx25 The `stub` method is on XCTest/XCTestCase, is there any particular reason you're not doing these from your tests?

**Comment by kylef** [comment]
The missing `matcher` is because you haven't provided a matcher to the stub method. See https://github.com/kylef/Mockingjay#usage

**Comment by istx25** [comment]
Does this library **only** support test cases? I am trying to stub network requests in the main target to provide a _fake_ response to network requests/prototype an application.

**Comment by kylef** [comment]
@istx25 That's possible, if you're using CocoaPods. You will want to depend on `Mockingjay/Core` to prevent XCTest being included.

The reason XCTest has it's own stub method, is because those `stub`s are removed at the end of the test case. You can instead add a stub yourself:

```swift
MockingjayProtocol.addStub(uri("/{user}/{repository}"), builder: json(data))
```

You can make a convenience global stub function as follows:

```swift
public func stub(matcher:Matcher, builder:Builder) -> Stub {
  return MockingjayProtocol.addStub(matcher, builder: builder)
}
```

I'll add a global `stub` method in the next release to make this easier.

**Comment by istx25** [comment]
Thanks!

**Comment by istx25** [comment]
I'll check this out. :)
