### ISSUE TITLE
stubbing dont working with Alamofire manager

### ISSUE THREAD

**Issue by andertsk** [kylef/Mockingjay#50]
Using the alamofire manager in test

[https://gist.github.com/andertsk/a72f65458542149f57f22974d63b312d](url)

results into failure. But if i use `Alamofire.request` - it's Ok. But i need to test with manager.

**Comment by kylef** [comment]
Hi @andertsk, the problem here is that you created a manager before the Mockingjay stub was added, thus the manager wasn't using Mockingjay.

I've made some changes in d6ccdc6 and released Mockingjay 1.2.1 which allows you to create a manager before registering stubs. Let me know if you're having any problems with this.

-Kyle
